Add config file
landoskape/networkAlignmentAnalysis pull request #56
Opened 2024-10-31 15:45 UTC by amazloumi

- Adding config files to centralize all the parameters in one place.
- No need to register paths (files.py will be removed).
- Organizing the parameters into different categories (model, dataset, training, optimizer, checkpointing, alignment, ... )

Closes #20 and #37.

2024-10-31 16:06 UTC, houman1359 approved these changes

2024-10-31 16:20 UTC, landoskape commented
This solution is fantastic, very happy to see configuration handled more effectively now.

2024-10-31 16:33 UTC, landoskape commented
A few questions / comments: 
1. I've never used omegaconf before, but should line 9 of the default_config.yaml have a capitalized ``False`` rather than ``false``?
2. Maybe instead of raising an exception when no timestamp is provided, we can just have the program define a date-time string automatically? (I know this was my original design, but looking at it again it seems silly). This is already implemented in the Experiment method ``register_timestamp``, so we just have to remove that block labeled `# do checks`. 
3. Now that the config file determines the "args" attribute, the ``get_args()`` method in ``experiment.py`` doesn't really make sense (at least it's name doesn't). Maybe we can move the device handling to the ``__init__`` method and make the ``meta_args`` list a class property.

2024-10-31 16:34 UTC, landoskape commented on configs/default_config.yaml
> +use_timestamp: false
False instead of false? 

(it might be okay, I haven't used omegaconf)

2024-10-31 16:35 UTC, landoskape commented on src/alignment/experiments/experiment.py
> +    def __init__(self, cfg) -> None:
maybe define meta_args as a class property rather than in the ``get_args()`` method.

2024-10-31 16:35 UTC, landoskape commented on src/alignment/experiments/experiment.py
> +        self.get_args()  # Parse arguments to python program
``get_args()`` is obsolete now

2024-10-31 16:36 UTC, landoskape commented on src/alignment/experiments/experiment.py
> +    def get_args(self):
get_args() is obsolete now. 

The device handling can be moved to the __init__ method, and the ``#do checks`` block can be deleted, since it's handled in``register_timestamp``

2024-10-31 16:38 UTC, amazloumi commented on src/alignment/experiments/experiment.py
> +    def __init__(self, cfg) -> None:
I am working on those extra methods in experiment.py. Like make_args, get_args.

It will be more cleaner.

2024-10-31 16:40 UTC, landoskape commented on src/alignment/experiments/experiment.py
> +    def __init__(self, cfg) -> None:
Ah I see, great

2024-10-31 20:54 UTC, amazloumi commented
> A few questions / comments:
> 
> 1. I've never used omegaconf before, but should line 9 of the default_config.yaml have a capitalized `False` rather than `false`?
> 2. Maybe instead of raising an exception when no timestamp is provided, we can just have the program define a date-time string automatically? (I know this was my original design, but looking at it again it seems silly). This is already implemented in the Experiment method `register_timestamp`, so we just have to remove that block labeled `# do checks`.
> 3. Now that the config file determines the "args" attribute, the `get_args()` method in `experiment.py` doesn't really make sense (at least it's name doesn't). Maybe we can move the device handling to the `__init__` method and make the `meta_args` list a class property.

@landoskape thanks for your comments:
1. We can use `false` or `False`. Both work but it is always good to be consistent.
2. The `# do checks` part is for when `just_plot` is enable and we have to have the previous `timestamp` to load the previous experiment. When we running a new experiment we don't need it.
3. Yes we removed the `make_args` and `arglib.py` completely, and for `get_arg` I have just remove the function and move the remaining code to `__init__` for now and leave further changes to following rounds of refactoring. 

Feel free to review the changes again. Thanks.

2024-11-01 11:44 UTC, landoskape commented
Thanks for explaining. It looks great to me!

2024-11-01 14:24 UTC, Naeemkh requested changes
Thank you, @amazloumi. While I review the functional components, could you please organize the import statements as follows:
- Standard Library Imports: Begin with Python's built-in modules (e.g., os).
- Blank Line: Insert a blank line after the standard library imports.
- Third-Party Imports: Follow with imports from external packages (e.g., torch).
- Blank Line: Insert another blank line after the third-party imports.
- Local Imports: Conclude with imports from the current project's modules.

This structure enhances code readability and aligns with Python's import conventions. Please read more here: https://peps.python.org/pep-0008/

2024-11-01 14:24 UTC, Naeemkh commented on experiment.py
> +from alignment.experiments.registry import create_experiment
Please add a new line between third party packages and internal imports.

2024-11-01 14:24 UTC, Naeemkh commented on src/alignment/config.py
> +from os import PathLike
Please use the following order for imports:

- Python internal modules
- Third party modules
- The package modules

Based on this, the os should move up.

2024-11-01 14:24 UTC, Naeemkh commented on src/alignment/experiments/registry.py
> +import sys
Please divide internal python lib and package imports by a new line.

2024-11-01 16:21 UTC, Naeemkh requested changes
@amazloumi, I think, we need to drop default from config filename and variable names.

2024-11-01 16:21 UTC, Naeemkh commented on configs/default_config.yaml
> +  default_wd: 0
The value in front of the parameter is the default value, I think, it does not make sense to add `default` to the parameter name.

2024-11-01 16:21 UTC, Naeemkh commented on src/alignment/config.py
> +    default_lr: float = 1e-3
Let's remove the default from the parameter name, if it being used as `default_lr` in the code, let's refactor it.

2024-11-01 16:21 UTC, Naeemkh commented on README.md
Please change the installation to the following:

```
pip install -e .[all]
```

2024-11-01 16:48 UTC, amazloumi commented on configs/default_config.yaml
> +  default_wd: 0
I agree.

2024-11-01 17:40 UTC, Naeemkh approved these changes

2024-11-01 17:40 UTC, houman1359 approved these changes

2024-11-01 17:43 UTC, merged